name: Audit Source Files
on: [workflow_dispatch]

jobs:
  audit:
    runs-on: windows-2022
    timeout-minutes: 120

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Fix LongPaths
        run: |
          git config --global core.longpaths true
          reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem" /v "LongPathsEnabled" /t REG_DWORD /d 1 /f
          python -m pip install httplib2==0.22.0 six

      - name: Clone Source Chromium 145
        run: python ungoogled-chromium/utils/clone.py -o build/src

      - name: Chay audit script
        run: python audit_script.py

      - name: Commit ket qua vao repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add audit_result.txt
          git commit -m "audit: ket qua kiem tra source"
          git push
