name: Build Custom Chromium Antidetect
on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Fix Long Paths & Dependencies
        run: |
          git config --global core.longpaths true
          reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem" /v "LongPathsEnabled" /t REG_DWORD /d 1 /f
          python -m pip install httplib2==0.22.0 six

      - name: Setup Sccache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Cache Persistence
        uses: actions/cache@v4
        with:
          path: ~/.cache/sccache
          key: sccache-${{ runner.os }}-${{ github.sha }}
          restore-keys: sccache-${{ runner.os }}-

      - name: Clone Source
        run: python ungoogled-chromium/utils/clone.py -o build/src

      - name: Apply Spoof Patcher
        id: patcher
        env:
          PYTHONUTF8: 1
        run: python spoof_patcher.py

      - name: Soi code tận ổ (Nếu lỗi)
        if: failure()
        run: |
          echo "--- SOI CODE NAVIGATOR_ID.CC ---"
          powershell -Command "if (Test-Path build/src/third_party/blink/renderer/core/frame/navigator_id.cc) { Select-String -Path build/src/third_party/blink/renderer/core/frame/navigator_id.cc -Pattern 'hardwareConcurrency' -Context 15,15 } else { echo 'File not found' }"

      - name: Official Build
        env:
          SCCACHE_GHA_ENABLED: "true"
          DEPOT_TOOLS_WIN_TOOLCHAIN: "0"
        run: |
          echo 'cc_wrapper="sccache"' >> flags.windows.gn
          python build.py
          python package.py

      - name: Export Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Antidetect-Chromium-Final
          path: build/*.zip
