name: Build Custom Chromium Antidetect
on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # --- SỬA LỖI FILENAME TOO LONG ---
      - name: Enable Long Paths
        run: |
          git config --global core.longpaths true
          reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem" /v "LongPathsEnabled" /t REG_DWORD /d 1 /f

      - name: Setup Sccache (Bảo hiểm đứt gánh)
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Cache Persistence
        uses: actions/cache@v4
        with:
          path: ~/.cache/sccache
          key: sccache-${{ runner.os }}-${{ github.sha }}
          restore-keys: sccache-${{ runner.os }}-

      - name: Clone Source
        run: python ungoogled-chromium/utils/clone.py -o build/src

      - name: Apply Spoof Patcher (Fake 24 tham số)
        run: python spoof_patcher.py

      - name: Official Build
        env:
          SCCACHE_GHA_ENABLED: "true"
        run: |
          echo 'cc_wrapper="sccache"' >> flags.windows.gn
          python build.py
          python package.py

      - name: Export Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Antidetect-Chromium-Final
          path: build/*.zip
