name: Build Antidetect Drive-Cache
on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Fix Environment & Install Rclone
        run: |
          git config --global core.longpaths true
          reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem" /v "LongPathsEnabled" /t REG_DWORD /d 1 /f
          python -m pip install httplib2==0.22.0 six
          choco install rclone -y

      - name: Setup Rclone Config
        shell: pwsh
        run: |
          # Tạo thư mục cấu hình
          New-Item -Directory -Path "$env:USERPROFILE\.config\rclone" -Force
          # Ghi file cấu hình bằng phương thức hệ thống để tránh lỗi mã hóa PowerShell
          $config = "[gdrive]`ntype = drive`nservice_account_contents = ${{ secrets.GDRIVE_JSON }}`nroot_folder_id = 1uznny42MrfIE4PSBOTEDfe34H46i6qkR"
          [System.IO.File]::WriteAllText("$env:USERPROFILE\.config\rclone\rclone.conf", $config)

      - name: Restore Cache from Drive
        run: |
          mkdir -p ~/.cache/sccache
          rclone sync gdrive:sccache ~/.cache/sccache --verbose
        continue-on-error: true

      - name: Setup Sccache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Clone Source
        run: python ungoogled-chromium/utils/clone.py -o build/src

      - name: Apply Spoof Patcher
        env: { PYTHONUTF8: 1 }
        run: python spoof_patcher.py

      - name: Official Build
        env:
          SCCACHE_GHA_ENABLED: "false"
          SCCACHE_DIR: "~/.cache/sccache"
        run: |
          echo 'cc_wrapper="sccache"' >> flags.windows.gn
          python build.py
          python package.py

      - name: Save Cache & Artifacts to Drive
        if: always()
        run: |
          rclone sync ~/.cache/sccache gdrive:sccache --verbose
          rclone copy build/ gdrive:Build_Thanh_Pham/ --include "*.zip" --include "*.exe"
